
# Referencia: este archivo es opcional si prefieres que Argo CD gestione el Secret.
# Por defecto, el script crea el Secret via kubectl y no usa este manifiesto.
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: redis-simple
type: Opaque
data:
  # reemplaza por tu base64
  redis-password: dXNlLXV0aWwtUkVESVMtcGFzcw==
